# Generated by Django 3.2 on 2021-04-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='photo',
            field=models.ImageField(default='not added', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='blogs',
            name='photo',
            field=models.ImageField(default='not added', upload_to='photos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='research',
            name='photo',
            field=models.ImageField(default='moy added', upload_to='photos'),
            preserve_default=False,
        ),
    ]
