# Generated by Django 3.2 on 2021-04-23 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20210417_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Contributors', models.CharField(max_length=500)),
                ('Story', models.TextField()),
                ('photo', models.ImageField(upload_to='photos')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_added'],
            },
        ),
        migrations.RenameModel(
            old_name='articles',
            new_name='article',
        ),
        migrations.RenameModel(
            old_name='blogs',
            new_name='blog',
        ),
        migrations.RenameModel(
            old_name='videos',
            new_name='video',
        ),
        migrations.DeleteModel(
            name='photos',
        ),
    ]
