# Generated by Django 3.2.4 on 2021-06-25 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210625_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Article_type',
            field=models.CharField(choices=[('State', 'State'), ('National', 'National'), ('Regional', 'Regional')], default='National', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='Language',
            field=models.CharField(choices=[('English', 'English'), ('Hindi', 'Hindi'), ('Urdu', 'Urdu'), ('Bengali', 'Bengali'), ('Marathi', 'Marathi'), ('Odia', 'Odia'), ('Telgu', 'Telgu'), ('Tamil', 'Tamil')], default='English', max_length=20),
        ),
    ]
