# Generated by Django 3.2 on 2021-04-15 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('Roll_Number', models.CharField(max_length=9)),
                ('FB_Handle', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='MembersPhoto')),
            ],
        ),
    ]
