# Generated by Django 3.2 on 2021-04-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='Insta_Id',
            field=models.CharField(default='not added', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='LinkedIn',
            field=models.CharField(default='not added', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='members',
            name='Twitter',
            field=models.CharField(default='not added', max_length=100),
            preserve_default=False,
        ),
    ]
