# Generated by Django 3.2 on 2021-04-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20210415_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
    ]
