# Generated by Django 3.2 on 2021-04-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_delete_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
        migrations.AddField(
            model_name='post',
            name='doc_link',
            field=models.CharField(default='none', max_length=400),
            preserve_default=False,
        ),
    ]
