# Generated by Django 3.2 on 2021-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210417_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='FB_Handle',
            new_name='Email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Insta_Id',
        ),
        migrations.RemoveField(
            model_name='members',
            name='LinkedIn',
        ),
        migrations.RemoveField(
            model_name='members',
            name='Twitter',
        ),
        migrations.AlterField(
            model_name='members',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='MembersPhoto'),
        ),
    ]
