# Generated by Django 3.2 on 2021-04-20 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_members_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='image_url',
            field=models.CharField(default='none', max_length=255),
            preserve_default=False,
        ),
    ]
