# Generated by Django 3.2 on 2021-04-20 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_members_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
