# Generated by Django 3.2 on 2021-04-20 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_members_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='image_url',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
